### ISSUE TITLE
missing documentation - replace pattern in the print dokumantation

### ISSUE THREAD

**Issue by wirkus** [mapbender/mapbender-documentation#174]
**Describe your feature request**
In the documentation is only an description for the YAML-Definition for the replace pattern. 

![replace_pattern](https://user-images.githubusercontent.com/2026210/80372890-85d3a980-8894-11ea-991f-4094e2a8c135.png)

Link:
* https://doc.mapbender.org/de/functions/export/printclient.html#yaml-definition
* https://github.com/mapbender/mapbender-documentation/blob/master/en/functions/export/printclient.rst

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8

**Improvement**
Description of a replace pattern definition for the element, e.g.

```
-                
  default: { 288: '&map_resolution=288' }
-
  pattern: 'mapbender_user'                     # oder es können für den Druck optimierte Dienste angefordert werden.
  replacement: { 288: 'mapbender_user_2' }
```

OR 

```
germany:
  pattern: /data/umn/germany/germany.map
  replacement:
    - /data/umn/germany/germany_4.map
mapbender:
  pattern: /data/umn/mapbender_user/mapbender_user.map
  replacement:
    - /data/umn/mapbender_user/mapbender_user_4.map

```

![replace_pattern 2](https://user-images.githubusercontent.com/2026210/80373533-7e60d000-8895-11ea-9987-4cf5f2c462df.png)
