### ISSUE TITLE
[yaml] add regionProperties documentation

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#420]
**Describe your feature request**
When an application is created via yaml you can define regionProperties to configure toolbar/sidepane/footer. (in the admin backend you do it at the gear button in the layout section)

- https://docs.mapbender.org/develop/de/backend/applications/layouts.html#sidepane-konfigurationsmoglichkeiten
- documentation for the backend is missing
- add the information to the workshop applications started with nrw demo https://github.com/mapbender/mapbender-workshop/blob/develop/config/applications/mapbender_demo_nrw.yaml#L11

```
              - name: toolbar
                properties:
                    item_alignment": right  # right/left/center
                    screenType: all         # desktop/mobile/all
                    generate_button_menu: false # true/false
                    menu_label: "Menu" # NULL or text
              - name: sidepane
                properties:
                    name: accordion # tabs (for button) / accordion / NULL
                    align: right # right/left
                    closed: false # true/false
                    screenType: all # all/desktop/mobile
                    width: "654px"
              - name: footer
                properties:
                    item_alignment": right # right/left/center
                    screenType: all # all/desktop/mobile
                    generate_button_menu: false # true/false
                    menu_label: "Menu" # NULL or text
```
