### ISSUE TITLE
mailer add documentation

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#433]
**Describe your feature request**
new configuration needs documentation

.env.local: MAILER_DSN=smtp://user:pass@smtp.example.com:25

- config/packages/fom.yaml:

```
fom_user:
    selfregister: false
    reset_password: true
    max_reset_time: 1
    mail_from_address: info@mapbender.org
    mail_from_name: Mapbender Team
```
