### ISSUE TITLE
View Manager - fix yaml documentation 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#437]
**Describe the bug**
The yaml Documenation is not complete and with typos. Please fix.
https://docs.mapbender.org/develop/en/elements/share/view_manager.html

```
                    viewmanager:
                        title: View Manager
                        class: Mapbender\CoreBundle\Element\ViewManager
                        publicEntries: rw          # String or empty (falsy value disables public entries entirely); other allowed values are ro (read only), rw (allow read and write), rwd (allow read and write and deletion) (default: ro)
                        privateEntries: true       # Turns user-private states on, with full usage (save, reapply, delete) (default: true)
                        allowAnonymousSave: true   # Extend right to save public entries also to anonymous users (default: false)
                        showDate: true             # Show date of creation or last update in entry listing (default: true)
```
