### ISSUE TITLE
searchRouter misses information about data-autocomplete-using

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#87]
SearchRouter has a parameter data-autocomplete-using

f.e.

`data-autocomplete-using: type  `

This parameter is not described properly  in the documentation. 

**imporvement**
Please describe all 3 data-autocomplete parameters in the text and provide good examples.

```
attr: 
                   data-autocomplete: on  # Attribut, um Autovervollständigung zu aktivieren
                   data-autocomplete-distinct: on  # Attribut, dass Autovervollständigung aktiviert aber unterscheiden lässt
                   data-autocomplete-using: type   # komma separierte Liste von anderen Eingabefeldern, in denen WHERE Angaben für die Autovervollständigung gemacht werden
```
* https://github.com/mapbender/mapbender-documentation/blob/master/en/functions/search/search_router.rst

see also: https://github.com/mapbender/mapbender-documentation/issues/75
